// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int32
	Name string
	Bio  pgtype.Text
}

type Book struct {
	ID          int32
	Title       string
	Description pgtype.Text
	NumCopy     int32
}

type BookAuthor struct {
	BookID   int32
	AuthorID int32
}

type BorrowedBook struct {
	ID         int32
	UserID     int32
	BookID     int32
	BorrowedAt pgtype.Timestamp
	ReturnedAt pgtype.Timestamp
}

type User struct {
	ID           int32
	Email        string
	Name         pgtype.Text
	Role         string
	PasswordHash string
	Nonce        string
}
